### ISSUE TITLE
refactor: refactor code into modular components on the frontend.

### ISSUE THREAD

**Issue by williamntlam** [williamntlam/frontend-code-sandbox#4]
# 📦 Frontend Code Refactor: Modular Components

**Issue Description**  
Refactor the existing frontend codebase into modular, reusable components to improve maintainability, scalability, and clarity. The goal is to follow best practices for component-based architecture while ensuring clean separation of concerns.

---

## 🚀 Goals  
- Break down large, monolithic code into smaller, reusable components.
- Ensure each component has a single responsibility.
- Improve code readability and maintainability.
- Make the project more scalable for future features.

---

## 🛠️ Tasks  
- [ ] Identify components that can be modularized.
- [ ] Create a `components/` directory for reusable UI components.
- [ ] Refactor large sections of code into smaller, self-contained components.
- [ ] Ensure proper naming conventions and file structure.
- [ ] Test components individually for functionality.
- [ ] Update documentation to reflect the new structure.

---

## 📁 Proposed Structure  
```plaintext
src/
├── components/        # Reusable UI components
│   ├── Editor/        # Code editor component
│   ├── Preview/       # Live preview component
│   ├── Header/        # Application header
│   └── Footer/        # Footer component
├── pages/             # Page-level components
│   ├── Home.tsx       # Main homepage
│   └── App.tsx        # Root application
├── utils/             # Utility functions
├── styles/            # Global styles (Tailwind / CSS Modules)
└── assets/            # Static files (icons, images)
```

---

## ✨ Acceptance Criteria  
- [ ] Code is broken down into modular components.
- [ ] Project structure matches the proposed structure.
- [ ] Components are reusable and easy to test.
- [ ] Documentation is updated.

---

## 🔄 Additional Context  
Provide any additional context or screenshots here if needed.
